### PR TITLE
Make Async a little bit smaller and faster

### PR DESCRIPTION
**Pull request by sopium**
By moving the `Drop` down to `source`, we can implement `into_inner` without using `Option` or 👽unsafe👽.

### CODE REVIEW

**Comment by zserik** [comment]
I think we could try to combine this with a partial fix for https://github.com/stjepang/smol/issues/142 and tie the cleanup to `Drop` of `Source` instead...

**Comment by sopium** [comment]
> I think we could try to combine this with a partial fix for #142 and tie the cleanup to a new `Drop` of `Source` instead...

I think you can use `Arc<SourceRegistration>` to enable the use case mentioned #142. But I don't think it's really worth it... Why not just use `Arc<Async<_>>`? Besides, it won't work for `dup`ed fds.

**Comment by zserik** [comment]
I wouldn't really like that stacking of `Arc`'s (that solution would use at least 2 `Arc`'s), but I probably would need to understand why `Arc<Source>` is used there in the first place. @stjepang

**Comment by stjepang** [comment]
Closing since this part of the codebase was moved into `async-io`.

**Pull request closed without merging**
