### PR TITLE
Refactor examples into its own crate

### PR DESCRIPTION
**Pull request by creativcoder**

### CODE REVIEW

**Comment by stjepang** [comment]
Thanks!! I think the only missing part now is setting up CI to check these examples. We might have to give cargo --all-features to make sure all examples are checked.

**Comment by creativcoder** [comment]
This line: https://github.com/stjepang/smol/blob/master/.github/workflows/build-and-test.yaml#L25?

**Comment by stjepang** [comment]
@creativcoder Yes, that's the line. Can you try that cargo check command to see if examples are checked? If not all of them are (other-runtimes.rs might get skipped), then try adding --all-features

**Comment by creativcoder** [comment]
@stjepang  Will check. Quick question, We will also need to create a cargo workspace toml; and move `smol` and `examples` as separate crates; right?

**Comment by stjepang** [comment]
@creativcoder I believe no extra steps like that are needed and you can just add a `[workspace]` section to the main `Cargo.toml`.

See how crossbeam does that here:
https://github.com/crossbeam-rs/crossbeam/blob/master/Cargo.toml#L66

**Comment by creativcoder** [comment]
@stjepang Have an issue, So we basically want to move dev-deps section to examples/Cargo.toml right?
So new structure would be:
```
smol/Cargo.toml
smol/examples/Cargo.toml
```

Having made those changes, I see that I can no longer compile and run examples within `/examples`. But if I go
to `/examples` and run `cargo run --example simple-client` just fine.

Am I missing anything in `smol/Cargo.toml`?

**Comment by stjepang** [comment]
I pushed some changes and it seems everything works as expected now except for what you mention @creativcoder.

@svartalf Do you perhaps know if there is a way around this? Is it possible to do `cargo run --example my_example` from the main directory without having to go into `examples/`?

**Comment by creativcoder** [comment]
Cool, thanks. These three dev-deps that has been added back to smol/Cargo.toml is because of the module tests, is it? 
```
[dev-dependencies]
futures = "0.3.4"
piper = "0.1.1"
num_cpus = "1.13.0"
```

As for examples directly, ideally we should be able to run examples from within root workspace; right?
Observation:
cargo detects examples directory by default, 
Setting `autoexamples = false`, it's not able to find `examples`, but if you remove `autoexamples` attr, examples are detected but it still fails to compile and the run the examples.

**Comment by svartalf** [comment]
@stjepang unfortunately, I can't think about any way to do that, after all it is a separate workspace crate. Best option I can suggest is to add `README.md` similar to [tokio one](https://github.com/tokio-rs/tokio/tree/master/examples#examples-of-how-to-use-tokio), which describes how to call them.

**Comment by stjepang** [comment]
Thanks!

**Comment by tshepang** [comment]
Why was this PR made... why make examples/ a separate crate?

**Comment by stjepang** [comment]
@tshepang Build were getting very slow because we had lots of big dev-dependencies, and we wanted to have a bit more control over each example.

Cargo still has some limitations and does not allow you to e.g. specify dependencies or features for each individual example.

So we moved examples into a separate crate. Other crates like heim and rayon do something similar.

**Pull request merged**
