### PR TITLE
Use actions-rs/install Action to speed up CI execution

### PR DESCRIPTION
**Pull request by svartalf**
It is possible to speed up CI a bit by using [actions-rs/install](https://github.com/actions-rs/install) Action, which speeds up binary crates installation (`grcov`, `cross` and `cargo-count` in `smol` case).

I feel obligated to point out that using this Action in a current state is potentially insecure, you can read more about it here: https://github.com/actions-rs/install/#tool-cache
It is the reason why this PR is in a draft state, so all maintainers can consider the situation first without accidentally merging it.

Also, note that `cargo-count` is not stored in the binary crates cache right now and this Action will fall back to usual `cargo install cargo-count` command, same as it was before in the workflow file.

### CODE REVIEW

**Comment by leo-lb** [comment]
@svartalf There should be no need for a centralized cache, Github Actions has caching with cache keys, I would think you can use that to cache installed binaries across jobs. That cache will be filled on the first run in a repo and then reused.

I think what takes the most time here is building the actual smol crate with all its dependencies and dev dependencies on all different platforms. I have found binary crates to be installed quite quickly.

**Comment by svartalf** [comment]
@leo-lb in general, I agree with you, that is the next step for this Action. Yet, as it was mentioned before multiple times, there is no programmatic access to this cache yet; current implementation with centralized cache acts like a temporary workaround for this problem.

As for installing binary crates - it usually takes a couple minutes, it is indeed not that big for `smol` right now, so I'm more that okay to close this PR without merging.

Based on the comparison of this branch `HEAD` and `v0.1.3` CI execution time it looks like "Code coverage" workflow runs ~1-2 min faster now, and "Security audit" went from ~5.5 min down to ~30 sec. Other workflows are not affected by this change.

**Comment by leo-lb** [comment]
@svartalf The speedups for Security Audit and Code Coverage are indeed significant, but as you said, I am not really in favor of a centralized cache, especially w.r.t security. Though, you probably already can compromise this repo because we import your action.rs scripts. I think that with the current Github Actions cache, it should be possible to synchronise ~/.cargo/bin in every job under the same cache key and maybe use cargo-update to bump the version when required. As for code, there should probably be separate caches with other keys, one for each platform and rust version. It should be possible to do without your actions.rs helpers, unless you tell Cargo to store artifacts in non-standard directories?

**Comment by svartalf** [comment]
@leo-lb sure, that's why I pointed the potential issues with security first :)

Yeah, you can try to cache `~/.cargo/bin`, and with Rust >= 1.41 you can just use `cargo install` now, as it will not perform re-compile each time if crate version [had not changed](https://github.com/rust-lang/rust/blob/master/RELEASES.md#cargo-2).

The only downside is that all other binaries will be stored in the cache too, including `cargo` itself, `rust-gdb`, `rustfmt` and whatever else there could be at `~/.cargo/bin`, so that cache key of yours at least should prevent misusing binaries from other toolchains.
For example, if toolchain is called "stable", it will not create separate cache entries for `1.41.0` and `1.42.0`, for example. It is solveable by using one of the `actions-rs/toolchain` [outputs](https://github.com/actions-rs/toolchain#outputs) and mixing the rustc build hash into the cache key, but there can be other potential papercuts too.

**Pull request closed without merging**
