### PR TITLE
Reexport other crates into smol

### PR DESCRIPTION
**Pull request by stjepang**
Look at the change in examples... thoughts?

### CODE REVIEW

**Comment by zicklag** [comment]
With a quick glance I think that looks good.

**Comment by wusyong** [comment]
Ah I updated my crate without knowing this pr is pending. I thought the reason to publish 0.2 is to make it split into separate crates and to be more modular. Import them back to smol seems to revert this work.

**Comment by Byron** [comment]
In #195 I remove `blocking` as it's not actually used in the crate. I noticed it's only used in the examples, but these won't work with blocking 0.5. To me it seems best to remove `blocking` for good and use `futures_lite` in the examples to block on a future.

**Comment by stjepang** [comment]
New release: https://docs.rs/smol/0.3

**Comment by Byron** [comment]
Here is an experience report of the past two days 😅🏃‍♂️

Yesterday I noticed that smol 0.2 was released, and I was about two days late for the game. Excited as I was, I left everything else I was working on to dive into async once again - a nice change of pace as well.

My crate of choice for porting to smol 0.2 is `prodash`, as it's quite simple and the `dashboard` example is a single file.
At first I was shocked - Smol became now more than an async executor, but the library docs fortunately hinted at the crates to look at. After all, this was the goal for a while now, split smol up into small crates. I didn't expect `smol` to shrink that radically though.

With my hand forced, and a little bit upset I started moving all usages of smol to their respective new subcrates. It was a bit like your sensai telling you to hit that wall of stone. Yes, it hurts, yes, it seems useless, but on the other side, enlightenment…awaits :D.

And step by step I realized what each of these parts are there for, and even better, each of them was small and thus easy to understand as needs be. Thanks to these tiny crates, you can now mix and match to get exactly what you need.
And since the new `smol` would create one thread available logical core by default, way too much for my taste, I ended up with… [copying the few lines it takes to implement it](https://github.com/crates-io/prodash/blob/f6fa7ab681549abfd77a14e4c8015f623f720c83/examples/dashboard.rs#L512), adjusted to only use a single thread and without tokio special casing.

The latter, make your own executor, was one of the goals of the preceding block posts and in a way, `smol`, and v0.2 was the version that forced me to try it out myself. Now `prodash` doesn't use smol anymore.

With the knowledge and experienced gained in 'easy mode', I moved on to the way bigger and more complex `criner`, which also used an upgrade. And this one felt quite a bit harder as for the first time, migrating to the individual building blocks I was forced to see what I was actually doing there! `criner` hat become a sinful mix of _all async_ that sometimes still wanted to run in its own thread because of growth over time, and blocking code that runs in async blocks. Even though it was initially disturbing to loose all the sugar that smol offered, it was a major eye opener and being there will help tremendously when inevitably cleaning it up.

And today we got v0.3, which brings back a lot (and probably more) features of smol 0.1, but shaped by all the lessons learned thus far. One feature I loved, having to bring up your own threads to drive the executor and thus controlling their amount, is now gone in favor of starting as many threads as the system has, automatically, but only when running the main future. I really like how it's done though, and once again learned something about the clever use of channels (which truly are ultra-powerful!).

Since only `criner` was left with a smol 0.2 runtime for my convenience, I decided to full replace that with an [in-crate version of smol 0.2](https://github.com/the-lean-crate/criner/blob/175184ad78ad3bbaece70f8acb7c7bbde9cd7d61/criner/src/smol.rs#L28) as well.

In a way, smol was truly successful in my codebase, in that it doesn't exist anymore ;).

Now there are only two big smudges left in my async story, namely being

* tokio - I need it because I need reqwest. And I need reqwest because I need async, TLS, redirect-following and per-chunk timeouts. You wouldn't believe what the Chinese firewall does to your application - unless there are timeouts, retries and resumable downloads everywhere, no download would ever finish. Maybe by now there is alternative clients, I would love one on `async-std` (or less) as the latter uses `smol`. Why would one not want tokio you might ask? Well, it's magically to me and I am too stupid to understand it. And `smol` has shown me the way, the way towards a future where everyone can hack on every detail of async. Nothing is magical.
* git2 - bindings to libgit2, and it's impossible to control timeouts so this thing will eventually hang forever. And even though it's isolated in a thread (♥️`blocking`), at some point the system will run out of file handles, which is somewhat unacceptable for a miner like `criner`. Of course you simply restart criner automatically when it goes down, but…Rust programs don't go down… unless the whole machine comes crashing down with it.

On the `git2` issue I am working now as kind of biiiiiig digression from where I came from, but I think now is the time to finally do it and scratch that decade-old itch of mine.
And maybe, maybe `surf` will be capable enough one day, but if you have another idea of what could replace `reqwest`, I am all ear.

Thanks for reading my unordered ramblings - it's late here and I better catch some sleep now.

**Comment by Keruspe** [comment]
@Byron you could give https://crates.io/crates/isahc a look, it's basically libcurl async bindings

**Pull request merged**
