### PR TITLE
Add Timer::{reset_at, reset_after}

### PR DESCRIPTION
**Pull request by sopium**
This is very useful for handling e.g. timeouts. Tokio, futures-timer or timerfd all have similar methods. The implementation is pretty straightforward.

### CODE REVIEW

**Comment by stjepang** [comment]
Could you perhaps say how this differs from reassigning timers like so?

```rust
my_timer = Timer::after(new_duration);
```

It seems to me `reset_after()` could be slightly more efficient, but I don't know how much it matters. Anyways, any reason why you prefer `reset_after()` over simply reassigning a timer?

**Comment by sopium** [comment]
> Could you perhaps say how this differs from reassigning timers like so?
> 
> ```rust
> my_timer = Timer::after(new_duration);
> ```
> 
> It seems to me `reset_after()` could be slightly more efficient, but I don't know how much it matters. Anyways, any reason why you prefer `reset_after()` over simply reassigning a timer?

Because I want to change a shared timer from a different task. See the test case. It does not work if you change it to

```
            *t1.lock().unwrap() = Timer::after(dur);
```

**Comment by stjepang** [comment]
Hmm. I wonder if dropping a `Timer` should wake the task waiting on it. What if we change this inside `fire_timers()`:

```rust
                    timers.remove(&(when, id));
```

to:

```rust
                    timers.remove(&(when, id)).map(|w| w.wake());
```

Then the test passes correctly. Perhaps we should do this regardless of this PR?

What if a task is waiting for a `Timer` but then that `Timer` is dropped? Should we wake the task?

**Comment by sopium** [comment]
> Hmm. I wonder if dropping a `Timer` should wake the task waiting on it. What if we change this inside `fire_timers()`:
> 
> ```rust
>                     timers.remove(&(when, id));
> ```
> 
> to:
> 
> ```rust
>                     timers.remove(&(when, id)).map(|w| w.wake());
> ```
> 
> Then the test passes correctly. Perhaps we should do this regardless of this PR?
> 
> What if a task is waiting for a `Timer` but then that `Timer` is dropped? Should we wake the task?

I don't know. It can be argued that when a timer is dropped, any interest on it is lost: #113.

**Comment by stjepang** [comment]
This now exists as `set_at()` and `set_after()`. Sorry for the delay - there was a lot of refactoring in flight so I didn't manage to pick up this PR!

**Pull request closed without merging**
