### PR TITLE
ci: test on a wider varitey of systems

### PR DESCRIPTION
**Pull request by dignifiedquire**

### CODE REVIEW

**Comment by stjepang** [comment]
Now that CI is working, let's rebase and see if this PR passes.

**Comment by stjepang** [comment]
Something's wrong with openssl on i686 - there may be a simple workaround...

**Comment by dignifiedquire** [comment]
cross doesn't have openssl, need to disable dependencies that require it, when using cross, or install a bundled version

**Comment by leo-lb** [comment]
I think it makes little sense to compile for more architectures if we can't also run tests on them too

**Comment by dignifiedquire** [comment]
@leo-lb it is running tests on those platforms as well

**Comment by stjepang** [comment]
Is this ready or still WIP? Asking because the PR looks ready to me :)

**Pull request merged**
