### PR TITLE
Check readable/writable flag before performing syscall

### PR DESCRIPTION
**Pull request by polachok**

### CODE REVIEW

**Comment by sopium** [comment]
Isn't this similar to tokio `PollEvented`? If i remembered correctly, it only supports one reading task and one writing task?

**Comment by polachok** [comment]
>Isn't this similar to tokio PollEvented?

Yes

>If i remembered correctly, it only supports one reading task and one writing task?

Multiple tasks can register wakers with one source.

**Comment by sopium** [comment]
> > If i remembered correctly, it only supports one reading task and one writing task?
> 
> Multiple tasks can register wakers with one source.

They can, but there can be races leading to lost wake-ups:

```
Task 1                      Reactor                        Task 2
read                                                        read
clear_readable
                         set readable
                         wake up task 1
                                                        clear_readable
check readable (oops)
```

I mentioned `PollEvented` because it is very similar and also have this limitation.

I'm not sure what your motivation is for this change, but you can use ticks to avoid the race: give each source a readable tick and writable tick. When the reactor received a readable/writable event, increment the tick. In `read_with`/`write_with`, load the tick first, then perform the IO operation, then waits for the tick to change if the operation returned `WouldBlock`. (This is to avoid another race I mentioned in #134, if edge-triggering is used.)

**Comment by stjepang** [comment]
The async-io crate now performs this optimization.

**Pull request closed without merging**
