### PR TITLE
Explain you must be in examples directory

### PR DESCRIPTION
**Pull request by stjepang**
Per this suggestion:

https://github.com/stjepang/smol/commit/69d808ff6893e098732763530e4b25395b1dacb6#commitcomment-38784070

### CODE REVIEW

**Comment by tshepang** [comment]
This is already mentioned in examples/readme file, or is that too hidden?

**Comment by stjepang** [comment]
Perhaps - I can imagine people attempting to run examples and not understanding why they are not working. So perhaps an extra notice would be helpful.

**Comment by PrototypeNM1** [comment]
> This is already mentioned in examples/readme file, or is that too hidden?

In my case returning to the readme when I'm already browsing examples wasn't my go to thought. Before that I jumped into cargo.toml and reasoned through it there.

**Comment by stjepang** [comment]
All right, I'm gonna merge this :) Extra instructions for running examples don't hurt!

**Pull request merged**
