### PR TITLE
Run code coverage CI on either master or pull request

### PR DESCRIPTION
**Pull request by wusyong**
I think code coverage workflow should only run on master.
Edit: Added pull request back.

### CODE REVIEW

**Comment by leo-lb** [comment]
I think it's useful to see the code coverage of pull requests if they add tests for example.

**Comment by leo-lb** [comment]
It was not reused, but I had already configured it some way in a previous PR because push + pull_request duplicates jobs in some conditions.

```yaml
on:
  push:
    branches:
      - master
  pull_request:
```

**Comment by stjepang** [comment]
I think I agree with @leo-lb here - if we're adding more tests, it'd be great to immediately see how they improve coverage.

**Comment by stjepang** [comment]
@leo-lb does this look good now?

**Comment by leo-lb** [comment]
@leo-lb Yes it does look good to me!

**Pull request merged**
