### PR TITLE
Fix lost reader wakeups

### PR DESCRIPTION
**Pull request by stjepang**

### CODE REVIEW

**Comment by stjepang** [comment]
@sopium Does this resolve #131?

**Comment by sopium** [comment]
> @sopium Does this resolve #131?

Yes, mostly.

**Comment by stjepang** [comment]
Hmmm, why "mostly"? :) What's missing?

**Comment by sopium** [comment]
> Hmmm, why "mostly"? :) What's missing?

It would be nice if it is not necessary to `poll` inside `read_with` to detect pipe reader closing, like in https://github.com/stjepang/smol/issues/131#issuecomment-633199262. The event flag (`EPOLLERR`) is already retrieved by `epoll_wait`. It's just not accessible to upper layers (`Source` and `Async`).

(FWIW, `tokio` `PollEvented` does give you the event flag: <https://docs.rs/tokio/0.2.21/tokio/io/struct.PollEvented.html#method.poll_read_ready>.)

But I understand that it requires perhaps substantial API and implementation changes. And there are workarounds: use `poll` like in the above comment or cascading `epollfd`s (like https://stackoverflow.com/a/46829067).

So I think this PR is good enough for now.

But maybe when we experiment with different reactor designs, implementations or APIs, we should try and see if the above problem can be solved more elegantly.

**Comment by stjepang** [comment]
Published v0.1.15 with this fix.

**Pull request merged**
