### PR TITLE
Fixed examples building

### PR DESCRIPTION
**Pull request by ahmed-masud**
merged Cargo.toml from examples/Cargo.toml.

This makes it possible to add examples into examples/ directory *without* having to explicitly add them into the [[examples]] array in Cargo.toml

If you wish to do a quick and dirty testing using the examples directory simply create it as examples/foo.rs or examples/foo/main.rs or examples/foo/lib.rs ; 

Note the trick of adding smol = "." alias in dev-dependencies :P which not needing `extern crate smol;`  in each example

### CODE REVIEW

**Comment by ahmed-masud** [comment]
... I did not want to fix the documentation in the examples on how to run them in this until you were okay with this.

**Comment by tshepang** [comment]
> Note the trick of adding smol = "." alias in dev-dependencies :P which not needing `extern crate smol;` in each example

I don't understand this... where is the alias?

**Comment by ahmed-masud** [comment]
https://github.com/stjepang/smol/pull/154#issuecomment-637336526

It's in top-level Cargo.toml in `[dev-dependencies]` section

**Comment by ahmed-masud** [comment]
If you are okay with these changes then I'll go clean up the examples documentation on how to run them.

Cheers

**Comment by ahmed-masud** [comment]
I tracked down why you moved them in to their own crate in the first place. Which was to make the CI build run faster (you mentioned this on May 1) so I guess this entire thing is moot? :P

**Comment by tshepang** [comment]
It could be that gha caching was addeed, which itself would solve the build CI problem.

**Comment by ahmed-masud** [comment]
> It could be that gha caching has since been added, which itself would solve the build CI problem.

I know that the checks above ran pretty fast for this PR ... if you like this change then I'll update the documentation.

**Comment by tshepang** [comment]
am happy with the change, but @stjepang is the one to decide

**Comment by stjepang** [comment]
I turned the examples directory into regular examples because there isn't much point in reducing smol's compilation time anymore. Smol is now just a small wrapper around the multitask crate. See #188

Thank you for this PR, though!

**Pull request closed without merging**
