### PR TITLE
Add CI build caching

### PR DESCRIPTION
**Pull request by leo-lb**

### CODE REVIEW

**Comment by stjepang** [comment]
This looks good and I'm inclined to merge.

@svartalf any objections?

**Comment by leo-lb** [comment]
@stjepang It's not ready yet

**Comment by leo-lb** [comment]
I realize it's not possible to achieve efficient caching at all with the current offered interface. See: https://github.com/actions/cache/issues/106#issuecomment-576418572

Caches are immutable, which means you can't write twice to the same cache-key. This means that a job must know before-hand, before fetching the cache, what key it wants, and if that key is not found, it will be set with the current job results. There's no way to cancel saving to cache if when you've tried to fetch from cache the cache-key wasnt found.

What we need is mutable access to caches by cache-key. Cargo builds incrementally, all previous data is interesting. It makes no sense to start from scratch, ever.

Cargo is unable to know if the cache is going to need to be updated unless it has access to data in this cache, chicken and egg situation.

And many things can affect cache, dependency update, rust version change, source code change, ...

**Comment by k-nasa** [comment]
Is it possible to include Cargo.lock in this repository?
If you do that, I think it will be solved by making Cargo.lock a cache key.

**Comment by k-nasa** [comment]
> Is it possible to include Cargo.lock in this repository?
If you do that, I think it will be solved by making Cargo.lock a cache key.

This is not a very good approach. It's not good to include Cargo.lock in your library.
I'm apologies.

**Comment by leo-lb** [comment]
@k-nasa it's not even relevant to the actual caching, many things outside of the Cargo.lock influence output artifacts

**Comment by leo-lb** [comment]
Basically the current approach does not allow us to construct caches incrementally, if you want a new cache you'll have to start building from scratch, and that's not interesting or efficient in the context of Rust

**Comment by Ekleog** [comment]
It's a whole new toolchain for people not yet used to it, but seeing where this is going I feel like I should suggest it: [nix](https://nixos.org/nix/) is a build system that can control the inputs that are used by `cargo`, using something like [crate2nix](https://github.com/kolloch/crate2nix) to convert a `Cargo.lock` (that, in this CI setup, could be auto-generated before calling crate2nix) into a nix-buildable file.

Then, once the nix-buildable file is generated, it's possible to use [the cachix action](https://github.com/marketplace/actions/cachix) to use [cachix](https://cachix.org/) (free for OSS projects) to cache each individual crate build.

The way `crate2nix` works should make it cache each downloaded crate source, as well as each dependency build that can be cached (ie. of which a dependency's version hasn't evolved), correctly for each rust version and target platform combination.

If you're interested about this toolchain there's help available on `#nixos-rust` on freenode; otherwise I can totally understand it's a brand “new” thing that'll require nontrivial investment to understand (though I personally feel like it's been well worth it), feel free to ignore this message :)

**Comment by leo-lb** [comment]
@Ekleog Cachix is an external service that is not Github - of course if you use an external service that is not Github you can do anything you want including mutable caches, but that's beside the point. I don't think we want to use an external caching service at this point.

**Comment by leo-lb** [comment]
Based on: https://github.com/wooferzfg/LiveSplitOne/blob/f1ab0d0603707b6b80ea01dd504c3f51690b1e45/.github/workflows/ci.yml#L20 - I added week number cache-keys

**Comment by leo-lb** [comment]
Besides the [ICE](https://github.com/stjepang/smol/runs/636941392#step:11:98) in cross compiling, this should be ready for merge

Commented on issue here: https://github.com/rust-lang/rust/issues/70924#issuecomment-622462659

**Comment by leo-lb** [comment]
Considering the current state of affairs, resetting all immutable caches every week is a simple solution that improves the current situation, even if not the most efficient. Until it's possible to do better, I guess let's leave it at that.

One thing that's no covered here is caching docker images with the cross compiling, but that's also problematic with Github Actions's caching so let's wait for Github to do better here.

**Comment by leo-lb** [comment]
@stjepang @svartalf Do we merge this? Any comments?

**Pull request merged**
